DOMAIN = "procurve"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_VERIFY_SSL = "verify_ssl"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_SNMP_COMMUNITY = "snmp_community"
CONF_SNMP_PORT = "snmp_port"

DEFAULT_PORT = 443
DEFAULT_USERNAME = "manager"
DEFAULT_VERIFY_SSL = False
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_SNMP_PORT = 161

API_VERSION_V8 = "v8"
API_VERSION_V7 = "v7"
API_VERSIONS_PROBE_ORDER = [API_VERSION_V8, API_VERSION_V7]
LOGIN_SESSIONS_PATH = "/login-sessions"
